### ISSUE TITLE
Is gtkspellmm related to gtkspell-code?

### ISSUE THREAD

**Issue by babycaseny** [manisandro/gtkspellmm#1]
I am trying to recompile poedit but failed on the gtkspell module.  I got the code gtkspell-code from sourceforge (See https://github.com/babycaseny/gtkspell-code) to recompile but got these errors:

autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
gtk-doc.make:83: warning: GTK_DOC_V_SETUP_$(V: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:84: warning: GTK_DOC_V_SETUP_$(AM_DEFAULT_VERBOSITY: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:104: warning: GTK_DOC_V_SCAN_$(V: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:105: warning: GTK_DOC_V_SCAN_$(AM_DEFAULT_VERBOSITY: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:108: warning: GTK_DOC_V_INTROSPECT_$(V: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:109: warning: GTK_DOC_V_INTROSPECT_$(AM_DEFAULT_VERBOSITY: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:140: warning: GTK_DOC_V_XML_$(V: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:141: warning: GTK_DOC_V_XML_$(AM_DEFAULT_VERBOSITY: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:157: warning: GTK_DOC_V_HTML_$(V: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:158: warning: GTK_DOC_V_HTML_$(AM_DEFAULT_VERBOSITY: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:161: warning: GTK_DOC_V_XREF_$(V: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:162: warning: GTK_DOC_V_XREF_$(AM_DEFAULT_VERBOSITY: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:193: warning: GTK_DOC_V_PDF_$(V: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
gtk-doc.make:194: warning: GTK_DOC_V_PDF_$(AM_DEFAULT_VERBOSITY: non-POSIX recursive variable expansion
docs/Makefile.am:93:   'gtk-doc.make' included from here
examples/Makefile.am:24: error: ENABLE_VAPIGEN does not appear in AM_CONDITIONAL
gtkspell/Makefile.am:53: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
gtkspell/Makefile.am:84: error: ENABLE_VAPIGEN does not appear in AM_CONDITIONAL
autoreconf: automake failed with exit status: 1

Then I came across with gtkspellmm.  I cloned but don't know how to cope with the original source code.  Any help? Was it something missed?

**Comment by manisandro** [comment]
gtkspellmm are the C++ bindings to gtkspell3

The upstream repositories for gtkspell3 and gtkspellmm are at

http://sourceforge.net/p/gtkspell/code/ci/default/tree/
http://sourceforge.net/p/gtkspell/gtkspellmm/ci/default/tree/

The error you are seeing is because you don't have all the necessary build dependencies installed (vala-devel, vala-tools, gobject-introspection-devel specifically). Though node that you don't necessarily need to regenerate the configure script via autogen.sh or autoreconf, just running ./configure is sufficient (and you won't need some of the build dependencies, depending on which components of gtkspell you need).

**Comment by babycaseny** [comment]
I have got gobject-introspection installed already, and gobject-introspection-devel is not available as package.  I run ./autogen.sh as running ./configure give the following error:

checking dependency style of gcc... (cached) gcc3
./configure: line 5107: syntax error near unexpected token `1.30.0'
./configure: line 5107: `GOBJECT_INTROSPECTION_CHECK(1.30.0)'

**Comment by manisandro** [comment]
gobject-introspection-devel is the name on Fedora, depending on what distro you are on the package name is likely different.
